import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';import {resolve,dirname} from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';
const base=resolve(dirname(fileURLToPath(import.meta.url)),'..'),out=resolve(process.argv[3]||'/tmp/cws-gate-b');await mkdir(out,{recursive:true});
const {chromium}=await import(pathToFileURL(resolve(process.argv[2])).href);const browser=await chromium.launch({headless:true,...(process.env.CORPORATE_TEST_BROWSER?{executablePath:process.env.CORPORATE_TEST_BROWSER}:{})});
const context=await browser.newContext({offline:true,viewport:{width:1440,height:900}}),page=await context.newPage(),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.dismiss());await context.route('**/*',r=>{if(/^https?:/.test(r.request().url())){requests.push(r.request().url());return r.abort();}return r.continue();});
try{
 await page.goto(pathToFileURL(resolve(base,'examples/six-slides.html')).href);await page.waitForFunction(()=>globalThis.CorporateApp);
 const original=await page.evaluate(()=>CorporateApp.getDeck());await page.locator('#theme-select').selectOption('hsbc-dark');
 const dark=await page.evaluate(()=>CorporateApp.getDeck());assert.equal(dark.theme.id,'hsbc-dark');dark.slides.forEach((s,i)=>s.elements.forEach((e,j)=>{for(const k of ['x','y','w','h','id'])assert.equal(e[k],original.slides[i].elements[j][k]);}));
 await page.locator('#mode').click();await page.locator('#edit-section').fill('开场');await page.locator('#edit-section').press('Tab');assert.equal(await page.locator('.section-heading').innerText(),'开场');
 await page.locator('#presenter').click();assert.ok(await page.locator('#presenter-panel').isVisible());assert.equal(await page.locator('#mode-label').innerText(),'展示模式');
 assert.equal(await page.locator('#next-stage .slide').getAttribute('data-slide-id'),'text');assert.equal(await page.locator('#presenter-notes').innerText(),original.slides[0].notes);
 await page.waitForFunction(()=>document.getElementById('timer').textContent!=='00:00');await page.locator('#timer-toggle').click();await page.locator('#timer-reset').click();assert.equal(await page.locator('#timer').innerText(),'00:00');assert.equal(await page.locator('#timer-toggle').innerText(),'继续计时');
 await page.locator('#black-screen').click();assert.ok(await page.locator('body').evaluate(e=>e.classList.contains('blackout')));await page.keyboard.press('b');assert.ok(!await page.locator('body').evaluate(e=>e.classList.contains('blackout')));
 await page.locator('#next').click();assert.equal(await page.locator('#next-stage .slide').getAttribute('data-slide-id'),'image');await page.locator('#presenter').click();assert.ok(!await page.locator('#presenter-panel').isVisible());
 await page.locator('#mode').click();await page.locator('#element-select').selectOption('text-body');await page.locator('#edit-hyperlink').fill('#chart');await page.locator('#edit-hyperlink').press('Tab');
 await page.locator('#mode').click();await page.locator('.slide.active [data-element-id="text-body"]').click();assert.equal(await page.evaluate(()=>CorporateApp.getDeck().slides[CorporateApp.getIndex()].id),'chart');
 await page.locator('#qa').click();assert.match(await page.locator('#message-title').innerText(),/质量检查/);await page.locator('#message button').click();
 const native=await page.evaluate(async()=>{const d=CorporateApp.getDeck();d.slides[0].elements[0].hyperlink='https://example.com/report';const z=await JSZip.loadAsync(await (await CorporateExport.toBlob(d)).arrayBuffer());return {ext:await z.file('ppt/slides/_rels/slide1.xml.rels').async('string'),internal:await z.file('ppt/slides/_rels/slide2.xml.rels').async('string')};});assert.match(native.ext,/https:\/\/example.com\/report/);assert.match(native.internal,/slides\/slide6.xml|slide6.xml/);
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);await page.screenshot({path:resolve(out,'presentation.png')});await writeFile(resolve(out,'gate-b-report.json'),JSON.stringify({status:'PASS',browser:await browser.version(),platform:process.platform,checks:['theme UI geometry preservation','section editor/list','presenter current/next/notes/timer/pause/reset/clock','black screen and keyboard','internal hyperlink UI','QA dialog','native external and internal hyperlinks','no requests']},null,2));console.log('PASS Gate B presentation UI and native hyperlinks');
}finally{await context.close();await browser.close();}
