/** Browser acceptance for canvas gestures, rich text, save/reopen, and native PPTX runs. */
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,mkdtemp} from 'node:fs/promises';
import {dirname,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {spawnSync} from 'node:child_process';

const base=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const modulePath=process.argv[2];if(!modulePath)throw new Error('Pass an existing Playwright module path; dependencies are not installed.');
const out=resolve(process.argv[3]||await mkdtemp(resolve(tmpdir(),'公司 富文本 测试 ')));await mkdir(out,{recursive:true});
const {chromium}=await import(pathToFileURL(resolve(modulePath)).href);
const browser=await chromium.launch({headless:true,...(process.env.CORPORATE_TEST_BROWSER?{executablePath:process.env.CORPORATE_TEST_BROWSER}:{})});
const context=await browser.newContext({offline:true,acceptDownloads:true,viewport:{width:1440,height:900}}),network=[],errors=[];
await context.route('**/*',route=>{if(/^https?:/.test(route.request().url())){network.push(route.request().url());return route.abort();}return route.continue();});
const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));page.on('dialog',dialog=>dialog.dismiss());
const snapshot=()=>page.evaluate(()=>CorporateApp.getDeck());
const open=async path=>{await page.goto(pathToFileURL(path).href);await page.waitForFunction(()=>!!globalThis.CorporateApp);assert.equal(await page.locator('#message').evaluate(el=>el.open),false,'initial model validates');};
const download=async(selector,path)=>{const pending=page.waitForEvent('download');await page.locator(selector).click();const item=await pending;await item.saveAs(path);assert.equal(await item.failure(),null);};
const change=async(selector,value)=>{await page.locator(selector).fill(value);await page.locator(selector).press('Tab');};
const python=process.env.CORPORATE_TEST_PYTHON||(process.platform==='win32'?'py':'python3');
const inspect=async(pptx,model)=>{
  const args=[...(process.platform==='win32'&&!process.env.CORPORATE_TEST_PYTHON?['-3']:[]),resolve(base,'tests/inspect_pptx.py'),pptx,'--model',model];
  const result=spawnSync(python,args,{encoding:'utf8'});assert.equal(result.status,0,result.stderr||result.error?.message||result.stdout);return JSON.parse(result.stdout);
};
const report={status:'PASS',browser:await browser.version(),platform:process.platform,offline:true,network:[],checks:[],officeUI:'NOT VERIFIED'};
try{
  await open(resolve(base,'examples/six-slides.html'));
  await page.locator('#mode').click();await page.locator('#slide-list li[data-slide-id="text"]').click();await page.locator('#element-select').selectOption('text-body');
  let model=await snapshot(),slide=model.slides.find(s=>s.id==='text'),body=slide.elements.find(e=>e.id==='text-body'),before={x:body.x,y:body.y,w:body.w,h:body.h};
  const object=page.locator('#stage .slide.active [data-element-id="text-body"]'),rect=await object.boundingBox();
  await page.mouse.move(rect.x+rect.width/2,rect.y+rect.height/2);await page.mouse.down();await page.mouse.move(rect.x+rect.width/2+30,rect.y+rect.height/2+12,{steps:4});await page.mouse.up();
  model=await snapshot();slide=model.slides.find(s=>s.id==='text');body=slide.elements.find(e=>e.id==='text-body');assert.ok(body.x!==before.x||body.y!==before.y,'drag changes canvas geometry');
  assert.ok(body.x>=0&&body.y>=0&&body.x+body.w<=1600&&body.y+body.h<=900);
  const afterDrag={x:body.x,y:body.y,w:body.w,h:body.h};await page.locator('#undo').click();
  let historyModel=await snapshot();assert.deepEqual(Object.fromEntries(['x','y','w','h'].map(k=>[k,historyModel.slides.find(s=>s.id==='text').elements.find(e=>e.id==='text-body')[k]])),before,'one undo restores the pre-drag object');
  await page.locator('#redo').click();
  const handle=page.locator('#stage .slide.active .selection-handle'),handleRect=await handle.boundingBox();
  await page.mouse.move(handleRect.x+handleRect.width/2,handleRect.y+handleRect.height/2);await page.mouse.down();await page.mouse.move(handleRect.x+handleRect.width/2+20,handleRect.y+handleRect.height/2+12,{steps:3});await page.mouse.up();
  model=await snapshot();body=model.slides.find(s=>s.id==='text').elements.find(e=>e.id==='text-body');assert.ok(body.w>afterDrag.w&&body.h>afterDrag.h,'resize handle scales the native object box');
  await page.locator('#element-select').selectOption('text-body');await page.keyboard.press('Shift+ArrowRight');
  model=await snapshot();body=model.slides.find(s=>s.id==='text').elements.find(e=>e.id==='text-body');assert.ok(body.x>afterDrag.x,'keyboard nudge commits geometry');
  await page.locator('#stage .slide.active [data-element-id="text-foot"]').click({modifiers:['Shift']});
  assert.match(await page.locator('#selection-hint').innerText(),/已选择 2 个对象/);
  await page.locator('[data-align="center"]').click();model=await snapshot();slide=model.slides.find(s=>s.id==='text');
  const centered=slide.elements.filter(e=>['text-body','text-foot'].includes(e.id));assert.ok(Math.abs(centered[0].x+centered[0].w/2-(centered[1].x+centered[1].w/2))<0.01,'selected text objects share a center');
  await page.locator('#element-select').selectOption('text-body');await page.locator('#rich-enable').click();
  await page.locator('#rich-paragraph').selectOption('0');await page.locator('#rich-align').selectOption('center');await page.locator('#rich-list').selectOption('bullet');await page.locator('#rich-bold').check();
  await change('#rich-size','36');await page.locator('#rich-color').fill('#c8102e');await page.locator('#rich-color').dispatchEvent('change');
  await change('#rich-link','https://example.com');await page.locator('#rich-add-run').click();await change('#rich-run-text','— 可复用方法');await page.locator('#rich-italic').check();
  await page.locator('#rich-add-paragraph').click();await page.locator('#rich-paragraph').selectOption('1');
  await change('#rich-run-text','编号步骤：形成可复用说明。');await page.locator('#rich-list').selectOption('number');await page.locator('#rich-indent').selectOption('1');
  await change('#edit-notes','Gate C 更新讲稿：富文本、画布位置和页面顺序已保存。');
  model=await snapshot();slide=model.slides.find(s=>s.id==='text');body=slide.elements.find(e=>e.id==='text-body');
  assert.ok(body.paragraphs?.length>=2);assert.equal(body.paragraphs[0].list,'bullet');assert.equal(body.paragraphs[0].align,'center');assert.equal(body.paragraphs[0].runs[0].bold,true);assert.equal(body.paragraphs[0].runs[1].italic,true);
  assert.equal(body.paragraphs[0].runs[0].fontSize,36);assert.equal(body.paragraphs[0].runs[0].color,'c8102e');assert.equal(body.paragraphs[0].runs[0].hyperlink,'https://example.com');
  assert.equal(body.paragraphs[1].list,'number');assert.equal(body.paragraphs[1].indent,1);assert.equal(body.text,body.paragraphs.map(p=>p.runs.map(r=>r.text).join('')).join('\n'));
  await page.locator('#element-select').selectOption('text-body');await page.locator('#color').fill('#171717');await page.locator('#color').dispatchEvent('change');
  await page.locator('#rich-link').fill('javascript:alert(1)');await page.locator('#rich-link').dispatchEvent('change');
  assert.match(await page.locator('#status').innerText(),/https, mailto/);await page.locator('#message form button').click();await page.locator('#rich-link').fill('https://example.com');await page.locator('#rich-link').dispatchEvent('change');
  await page.locator('#slide-list li[data-slide-id="image"]').dragTo(page.locator('#slide-list li[data-slide-id="cover"]'));
  model=await snapshot();assert.equal(model.slides[0].id,'image');
  const expected=model,html=resolve(out,'完整 保存 中文 演示.html');await download('#save',html);
  const fresh=await browser.newContext({offline:true}),reopened=await fresh.newPage();await reopened.goto(pathToFileURL(html).href);await reopened.waitForFunction(()=>!!globalThis.CorporateApp);
  assert.deepEqual(await reopened.evaluate(()=>CorporateApp.getDeck()),expected,'downloaded full HTML reopens with the exact latest model');await fresh.close();
  await page.waitForFunction(()=>CorporateApp.overflow().length===0);const modelFile=resolve(out,'最新演示.json');await writeFile(modelFile,JSON.stringify(expected,null,2));
  const pptx=resolve(out,'富文本与画布编辑后.pptx');await download('#export',pptx);report.pptx=await inspect(pptx,modelFile);
  const current=await readFile(pptx);report.pptxBytes=current.length;
  assert.ok(report.pptx.slides===6&&report.pptx.notes===6&&report.pptx.charts>=1&&report.pptx.tables>=1&&report.pptx.pictures>=1);
  assert.deepEqual(network,[]);assert.deepEqual(errors,[]);report.network=network;
  report.checks=['canvas pointer drag with bounds','multi-object resize','arrow-key nudge','shift multi-select and center alignment','structured paragraphs, numbering, bullets, paragraph alignment and styled native runs','safe hyperlink validation','drag reorder','HTML download and fresh offline reopen exact equality','latest model native PPTX with notes, picture, table, chart, and text objects'];
  await writeFile(resolve(out,'gate-c-browser.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await context.close();await browser.close();}
